#%Module 1.0
#
#  MPICH module for use with 'environment-modules' package:
# 

# Define prefix so PATH and MANPATH can be updated.
setenv        prefix        /home/gavahi/CryptMPI_2022/MPICH/cryptMPI-mpich-3.3/Install_mpich
setenv        exec_prefix   ${prefix}
prepend-path  PATH          ${exec_prefix}/bin
prepend-path  MANPATH       ${prefix}/share/man

# Undefine prefix and exec_prefix which are too generic environment variables.
unsetenv      prefix
unsetenv      exec_prefix
